version: '3.1'

services:
  web:
    image: php:8.0-apache
    container_name: php_web_webapp3
    build:
      context: .
      dockerfile: Dockerfile-php
    restart: always
    ports:
      - "8009:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    # Bart beun oplossing voor MAC OS
    # platform: linux/x86_64
    image: mysql:5.7
    container_name: mysql_db_webapp3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_webapp3
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - db

volumes:
  db_data:
